package grpc

// This file contains hand-written protobuf message types and gRPC service
// registration that mirror the definitions in proto/user.proto.
// In production, these would be generated by protoc with protoc-gen-go
// and protoc-gen-go-grpc. This approach uses a JSON codec so the service
// compiles and runs without requiring generated protobuf code.

import (
	"context"
	"encoding/json"
	"fmt"

	grpclib "google.golang.org/grpc"
	"google.golang.org/grpc/encoding"
)

func init() {
	// Register a JSON codec so gRPC can marshal/unmarshal our plain Go structs.
	// The default "proto" codec expects proto.Message; this override handles
	// our hand-written types until proper protoc generation is set up.
	encoding.RegisterCodec(JSONCodec{})
}

// JSONCodec implements grpc encoding.Codec using JSON serialization.
type JSONCodec struct{}

// Marshal serializes v to JSON bytes.
func (JSONCodec) Marshal(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

// Unmarshal deserializes JSON bytes into v.
func (JSONCodec) Unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

// Name returns the codec name registered with gRPC.
func (JSONCodec) Name() string {
	return "proto"
}

// ── Request messages ──

// GetUserRequest mirrors the proto GetUserRequest.
type GetUserRequest struct {
	UserId string `json:"user_id"`
}

// GetUsersBatchRequest mirrors the proto GetUsersBatchRequest.
type GetUsersBatchRequest struct {
	UserIds []string `json:"user_ids"`
}

// ValidateTokenRequest mirrors the proto ValidateTokenRequest.
type ValidateTokenRequest struct {
	Token string `json:"token"`
}

// VerificationRequest mirrors the proto VerificationRequest.
type VerificationRequest struct {
	UserId       string `json:"user_id"`
	InmateNumber string `json:"inmate_number"`
}

// PermissionRequest mirrors the proto PermissionRequest.
type PermissionRequest struct {
	UserId string `json:"user_id"`
}

// ── Response messages ──

// UserResponse mirrors the proto UserResponse.
type UserResponse struct {
	Id               string  `json:"id"`
	Username         string  `json:"username"`
	DisplayName      string  `json:"display_name"`
	Avatar           *string `json:"avatar,omitempty"`
	Bio              *string `json:"bio,omitempty"`
	Role             string  `json:"role"`
	InmateNumber     *string `json:"inmate_number,omitempty"`
	ProfileVerified  bool    `json:"profile_verified"`
	RepresentativeId *string `json:"representative_id,omitempty"`
	FollowersCount   int64   `json:"followers_count"`
	FollowingCount   int64   `json:"following_count"`
	PostsCount       int64   `json:"posts_count"`
	CreatedAt        string  `json:"created_at"`
}

// GetUsersBatchResponse mirrors the proto GetUsersBatchResponse.
type GetUsersBatchResponse struct {
	Users []*UserResponse `json:"users"`
}

// ValidateTokenResponse mirrors the proto ValidateTokenResponse.
type ValidateTokenResponse struct {
	Valid  bool   `json:"valid"`
	UserId string `json:"user_id"`
	Role   string `json:"role"`
}

// VerificationResponse mirrors the proto VerificationResponse.
type VerificationResponse struct {
	IsVerified          bool     `json:"is_verified"`
	AllowedContentTypes []string `json:"allowed_content_types"`
}

// PermissionResponse mirrors the proto PermissionResponse.
type PermissionResponse struct {
	CanUpload           bool     `json:"can_upload"`
	AllowedContentTypes []string `json:"allowed_content_types"`
	MaxFileSizeBytes    int64    `json:"max_file_size_bytes"`
}

// ── Service interface and registration ──

// UserServiceServer is the server API for UserService.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	GetUsersBatch(context.Context, *GetUsersBatchRequest) (*GetUsersBatchResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	VerifyUserForContentUpload(context.Context, *VerificationRequest) (*VerificationResponse, error)
	GetUserContentPermissions(context.Context, *PermissionRequest) (*PermissionResponse, error)
}

// UnimplementedUserServiceServer provides default implementations returning unimplemented errors.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, fmt.Errorf("rpc GetUser not implemented")
}
func (UnimplementedUserServiceServer) GetUsersBatch(context.Context, *GetUsersBatchRequest) (*GetUsersBatchResponse, error) {
	return nil, fmt.Errorf("rpc GetUsersBatch not implemented")
}
func (UnimplementedUserServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, fmt.Errorf("rpc ValidateToken not implemented")
}
func (UnimplementedUserServiceServer) VerifyUserForContentUpload(context.Context, *VerificationRequest) (*VerificationResponse, error) {
	return nil, fmt.Errorf("rpc VerifyUserForContentUpload not implemented")
}
func (UnimplementedUserServiceServer) GetUserContentPermissions(context.Context, *PermissionRequest) (*PermissionResponse, error) {
	return nil, fmt.Errorf("rpc GetUserContentPermissions not implemented")
}

// serviceDesc is the gRPC ServiceDesc for UserService.
var serviceDesc = grpclib.ServiceDesc{
	ServiceName: "atto.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpclib.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    getUserHandler,
		},
		{
			MethodName: "GetUsersBatch",
			Handler:    getUsersBatchHandler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    validateTokenHandler,
		},
		{
			MethodName: "VerifyUserForContentUpload",
			Handler:    verifyUserForContentUploadHandler,
		},
		{
			MethodName: "GetUserContentPermissions",
			Handler:    getUserContentPermissionsHandler,
		},
	},
	Streams: []grpclib.StreamDesc{},
}

// RegisterUserServiceServer registers the UserServiceServer with the gRPC server.
func RegisterUserServiceServer(s *grpclib.Server, srv UserServiceServer) {
	s.RegisterService(&serviceDesc, srv)
}

// ── Method handlers ──

func getUserHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpclib.UnaryServerInterceptor) (interface{}, error) {
	req := &GetUserRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, req)
	}
	info := &grpclib.UnaryServerInfo{Server: srv, FullMethod: "/atto.user.UserService/GetUser"}
	handler := func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, r.(*GetUserRequest))
	}
	return interceptor(ctx, req, info, handler)
}

func getUsersBatchHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpclib.UnaryServerInterceptor) (interface{}, error) {
	req := &GetUsersBatchRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsersBatch(ctx, req)
	}
	info := &grpclib.UnaryServerInfo{Server: srv, FullMethod: "/atto.user.UserService/GetUsersBatch"}
	handler := func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsersBatch(ctx, r.(*GetUsersBatchRequest))
	}
	return interceptor(ctx, req, info, handler)
}

func validateTokenHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpclib.UnaryServerInterceptor) (interface{}, error) {
	req := &ValidateTokenRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateToken(ctx, req)
	}
	info := &grpclib.UnaryServerInfo{Server: srv, FullMethod: "/atto.user.UserService/ValidateToken"}
	handler := func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateToken(ctx, r.(*ValidateTokenRequest))
	}
	return interceptor(ctx, req, info, handler)
}

func verifyUserForContentUploadHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpclib.UnaryServerInterceptor) (interface{}, error) {
	req := &VerificationRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyUserForContentUpload(ctx, req)
	}
	info := &grpclib.UnaryServerInfo{Server: srv, FullMethod: "/atto.user.UserService/VerifyUserForContentUpload"}
	handler := func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyUserForContentUpload(ctx, r.(*VerificationRequest))
	}
	return interceptor(ctx, req, info, handler)
}

func getUserContentPermissionsHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpclib.UnaryServerInterceptor) (interface{}, error) {
	req := &PermissionRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserContentPermissions(ctx, req)
	}
	info := &grpclib.UnaryServerInfo{Server: srv, FullMethod: "/atto.user.UserService/GetUserContentPermissions"}
	handler := func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserContentPermissions(ctx, r.(*PermissionRequest))
	}
	return interceptor(ctx, req, info, handler)
}
